src/groups/urls.py
# -*- coding:utf-8 -*-
from django.conf.urls import url
from src.groups import views

urlpatterns = [
    url(r'^$', views.GroupListView.as_view(), name='groups'),
    url(r'^(?P<group_id>[0-9]+)/$', views.GroupView.as_view(), name='group'),
    url(r'^(?P<group_id>[0-9]+)/courses/(?P<group_course_id>[0-9]+)/$',
        views.GroupCourseView.as_view(),
        name='group-course'
    ),
    url(r'^(?P<group_id>[0-9]+)/courses/(?P<group_course_id>[0-9]+)/solutions/$',
        views.GroupCourseSolutionsView.as_view(),
        name='group-course-solutions'
    ),
]

src/profile/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url('^login/$', views.LoginView.as_view(), name='login'),
    url('^logout/$', views.logout, name='logout'),
    # url('^signup/$', views.SignUpView.as_view(), name='signup'),
]

src/training/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^$', views.CourseListView.as_view(), name='courses'),
    url('^(?P<course>[a-z0-9-]+)/$', views.CourseView.as_view(), name='course'),
    url('^(?P<course>[a-z0-9-]+)/solutions/$', views.CourseSolutionsView.as_view(), name='course-solutions'),
    url('^(?P<course>[a-z0-9-]+)/(?P<topic>[a-z0-9-]+)/$', views.TopicView.as_view(), name='topic'),
    url('^(?P<course>[a-z0-9-]+)/(?P<topic>[a-z0-9-]+)/(?P<taskitem>[a-z0-9-]+)/$', views.TaskItemView.as_view(), name='taskitem'),
    url('^(?P<course>[a-z0-9-]+)/(?P<topic>[a-z0-9-]+)/(?P<taskitem>[a-z0-9-]+)/solution/$', views.SolutionView.as_view(), name='solution'),
]

src/urls.py
from django.conf.urls import url, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.views.static import serve
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^courses/', include('src.training.urls', namespace='training')),
    url(r'^groups/', include('src.groups.urls', namespace='groups')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('src.profile.urls', namespace='profile')),
    url(r'^$', TemplateView.as_view(template_name='frontpage.html'))
]

# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns = [
#         url('__debug__/', include(debug_toolbar.urls)),
#     ] + urlpatterns
#

try:
    from src.service.models import SiteSettings
    admin.site.site_header = SiteSettings.objects.get(id=settings.SITE_ID).name
except:
    pass

src/groups/views.py
from django.shortcuts import render, Http404, redirect
from django.http import JsonResponse
from django.urls import reverse
from django.core.exceptions import PermissionDenied
from django.utils.decorators import method_decorator
from django.views.generic import View
from src.groups.models import Group, GroupCourse, GroupMember
from src.groups.forms import GroupSearchForm, GroupInviteForm


class GroupListView(View):

    def get(self, request, *args, **kwargs):
        objects = Group.objects.filter(show=True).prefetch_related('_members')
        search = request.GET.get('search')
        form = GroupSearchForm(data=request.GET)
        if search:
            objects = objects.filter(title__icontains=search)

        return render(
            template_name='groups/groups_list.html',
            context={
                'objects': objects,
                'form': form
            },
            request=request
        )


class GroupView(View):

    def get_object(self,  *args, **kwargs):

        return Group.objects.prefetch_related('_members').get(id=kwargs['group_id'])

    def get(self, request, *args, **kwargs):

        group = self.get_object(*args, **kwargs)
        form = None
        if request.user.is_active:
            if request.user not in group.members:
                form = GroupInviteForm(instance=group)
        return render(
            template_name='groups/group.html',
            context={
                'object': group,
                'form': form,
                'user_is_member': request.user in group.members,
                'user_is_teacher': request.user == group.author,
            },
            request=request
        )

    def post(self, request, *args, **kwargs):
        if request.user.is_active:
            group = self.get_object(*args, **kwargs)
            form = GroupInviteForm(instance=group, data=request.POST)
            user_is_member = request.user in group.members
            if not user_is_member:
                if form.is_valid():
                    GroupMember.objects.create(group=group, user=request.user)
                    user_is_member = True
                    form = None
                return render(
                    template_name='groups/group.html',
                    context={
                        'object': group,
                        'form': form,
                        'user_is_member': user_is_member
                    },
                    request=request
                )
            return redirect(reverse('groups:group', kwargs={'group_id': group.id}))

        raise Http404


class GroupCourseView(View):

    def get_object(self, *args, **kwargs):
        try:
            group_course = GroupCourse.objects.select_related('group', 'course').get(id=kwargs['group_course_id'])
        except:
            raise Http404
        else:
            if not group_course.show_table:
                raise Http404
            return group_course

    def get(self, request, *args, **kwargs):
        group_course = self.get_object(*args, **kwargs)
        group = group_course.group
        if(request.user == group.author or request.user in group.members):
            return render(
                request=request,
                template_name='groups/group_course.html',
                context={
                    'object': group_course,
                    'course_data': group_course.course.get_cache_data()
                }
            )
        else:
            raise Http404


class GroupCourseSolutionsView(View):

    def get_object(self, *args, **kwargs):
        try:
            group_course = GroupCourse.objects.select_related('group', 'course').get(id=kwargs['group_course_id'])
        except:
            raise Http404
        else:
            if not group_course.show_table:
                raise Http404
            return group_course

    def get(self, request, *args, **kwargs):
        group_course = self.get_object(request, *args, **kwargs)
        group = group_course.group
        course = group_course.course
        result = {}
        for user in group.members:
            result['member-%d' % user.id] = {
                'full_name': user.get_full_name(),
                'data': user.get_cache_course_solutions_data(course),
                'show_link': request.user.is_superuser or
                             request.user == user or
                             request.user == group.author
            }
        return JsonResponse(result)

src/profile/views.py
from django.views.generic import View
from django.shortcuts import HttpResponse, render, redirect
from src.profile.forms import LoginForm, SignupForm
from django.contrib.auth import login, logout as auth_logout
from urllib import parse


class LoginView(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_active:
            return redirect('/')
        next = parse.urlparse(request.META.get('HTTP_REFERER', '/')).path
        return render(
            request=request,
            template_name='profile/login.html',
            context={'form': LoginForm(request=request, initial={'next': next})}
        )

    def post(self, request, *args, **kwargs):
        form = LoginForm(request=request, data=request.POST)
        if form.is_valid():
            login(request, form.user)
            return redirect(form.cleaned_data.get('next', '/'))
        else:
            return render(
                request=request,
                template_name='profile/login.html',
                context={'form': form}
            )


def logout(request, *args, **kwargs):
    # TODO оставлять на той же странице, если есть права, иначе на главную
    # next = parse.urlparse(request.META.get('HTTP_REFERER', '/')).path
    auth_logout(request)
    return redirect('/')


class SignUpView(View):

    def get(self, request, *args, **kwargs):
        if request.user.is_active:
            return redirect('/')
        next = parse.urlparse(request.META.get('HTTP_REFERER', '/')).path
        return render(
            request=request,
            template_name='profile/signup.html',
            context={'form': SignupForm(initial={'next': next})}
        )

    def post(self, request, *args, **kwargs):
        form = SignupForm(data=request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            return redirect(form.cleaned_data.get('next', '/'))
        else:
            return render(
                request=request,
                template_name='profile/signup.html',
                context={'form': form}
            )

src/training/views/course.py
# -*- coding:utf-8 -*-
from django.shortcuts import render, Http404
from django.views.generic import View
from django.utils.decorators import method_decorator
from src.training.models import Course


class CourseListView(View):

    def get(self, request, *args, **kwargs):
        return render(
            template_name='training/course_list.html',
            context={'objects': Course.objects.filter(show=True)},
            request=request
        )


class CourseView(View):

    def get_object(self, request, *args, **kwargs):
        try:
            return Course.objects.select_related('lang').get(slug=kwargs['course'])
        except Course.DoesNotExist:
            raise Http404

    def get(self, request, *args, **kwargs):
        course = self.get_object(request, *args, **kwargs)
        return render(
            template_name='training/course.html',
            context={
                'object': course,
                'course': course,
            },
            request=request
        )

src/training/views/taskitem.py
# -*- coding:utf-8 -*-
from django.contrib.auth import get_user_model
from django.http import JsonResponse
from django.shortcuts import render, Http404
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from django.utils.decorators import method_decorator
from django.views.generic import View
from src.training.models import TaskItem, Solution, Course
from src.training.forms import TaskItemForm, SolutionForm


UserModel = get_user_model()


class TaskItemView(View):

    def get_object(self, request, *args, **kwargs):
        try:
            return TaskItem.objects \
                .select_related('task', 'topic__course', 'topic__course__lang') \
                .get(slug=kwargs['taskitem'], topic__slug=kwargs['topic'], topic__course__slug=kwargs['course'])
        except TaskItem.DoesNotExist:
            raise Http404

    def get(self, request, *args, **kwargs):
        taskitem = self.get_object(request,  *args, **kwargs)
        solution = None
        form_initial = {'lang': taskitem.lang.provider_name}
        if request.user.is_active:
            solution = Solution.objects.filter(taskitem=taskitem, user=request.user).first()
            if solution:
                form_initial['content'] = solution.last_changes
        form = TaskItemForm(initial=form_initial)
        return render(
            request=request,
            template_name='training/taskitem/template.html',
            context={
                'course': taskitem.topic.course,
                'object': taskitem,
                'solution': solution,
                'form': form
            }
        )

    def post(self, request, *args, **kwargs):
        taskitem = self.get_object(request, *args, **kwargs)
        form = TaskItemForm(data=request.POST)
        response = form.perform_operation(request.user, taskitem)
        return JsonResponse(response.__dict__)


class SolutionView(View):

    PERM_DENIED = 0
    VIEW_PERM = 1
    CHANGE_PERM = 2

    def get_solution_user_id(self, request) -> int:

        """ Возвращает id пользователя, чье решение запрашивается

        Возможно 3 варианта:
            - в get-параметра 'user' указан id целевого пользователя
            - get-параметр не указан, тогда возвращает id текущего пользователя
            - get-параметр не целое число, тога возбуждаем 404 ошибку
        """

        target_user_id = request.GET.get('user')
        if target_user_id is None:
            solution_user_id = int(request.user.id)
        elif target_user_id.isdigit():
            solution_user_id = int(target_user_id)
        else:
            raise Http404
        return solution_user_id

    def get_user_perm(self, request, solution_user_id: int) -> int:

        """
        Возвращает права пользователя на запрашиваемое решение:

            Доступ к просмотру решения имеют 3 группы пользователей:
            1. Суперпользователь
            2. Автор решения
            3. Автор группы (учитель) в которой состоит пользователь (ученик)

            Доступ к редактированию решения имеют 2 группы пользователей:
            1. Суперпользователь
            2. Автор группы (учитель) в которой состоит пользователь (ученик)

        """
        if request.user.is_superuser:
            perm = self.CHANGE_PERM
        else:
            solution_user = UserModel.objects.filter(id=solution_user_id).first()
            if solution_user.member.filter(group__author=request.user).exists():  # преподаватель в группе ученика
                perm = self.CHANGE_PERM
            elif solution_user_id == request.user.id:  # просмотр собственного решения
                perm = self.VIEW_PERM
            else:
                perm = self.PERM_DENIED
        return perm

    def get_object(self, user_id, **kwargs) -> Solution:
        filter = {
            "taskitem__slug": kwargs['taskitem'],
            "taskitem__topic__slug": kwargs['topic'],
            "taskitem__topic__course__slug": kwargs['course'],
            "user_id": user_id
        }
        try:
            return Solution.objects.get(**filter)
        except MultipleObjectsReturned:
            # TODO Логировать ошибку
            return Solution.objects.filter(**filter).first()
        except ObjectDoesNotExist:
            raise Http404

    def get(self, request, *args, **kwargs):
        solution_user_id = self.get_solution_user_id(request)
        solution = self.get_object(user_id=solution_user_id, **kwargs)
        request_user_perm = self.get_user_perm(request, solution_user_id)
        form = None
        if request_user_perm == self.CHANGE_PERM and solution.taskitem.manual_check:
            form = SolutionForm(instance=solution)
        elif request_user_perm == self.PERM_DENIED:
            raise Http404

        return render(
            request,
            template_name='training/solution/template.html',
            context={
                'object': solution,
                'form': form,
                'course': solution.taskitem.topic.course,
                'topic': solution.taskitem.topic
            }
        )

    def post(self, request, *args, **kwargs):
        solution_user_id = self.get_solution_user_id(request)
        solution = self.get_object(user_id=solution_user_id, **kwargs)
        request_user_perm = self.get_user_perm(request, solution_user_id)
        if request_user_perm == self.CHANGE_PERM and solution.taskitem.manual_check:
            form = SolutionForm(instance=solution, data=request.POST)
            if form.is_valid():
                solution = form.save(commit=False)
                solution.teacher = request.user
                solution.save()
        else:
            raise Http404
        return render(
            request,
            template_name='training/solution/template.html',
            context={
                'object': solution,
                'form': form,
                'course': solution.taskitem.topic.course,
                'topic': solution.taskitem.topic
            }
        )


class CourseSolutionsView(View):

    def get(self, request, *args, **kwargs):
        try:
            course = Course.objects.get(slug=kwargs.get('course'))
            user_id = request.GET['user_id']
            user = UserModel.objects.get(id=user_id, is_active=True)
            return JsonResponse(user.get_cache_course_solutions_data(course))
        except:
            raise Http404

src/training/views/topic.py
# -*- coding:utf-8 -*-
from django.views.generic import View
from django.http import JsonResponse
from django.shortcuts import render, Http404
from django.utils.decorators import method_decorator
from src.training.forms import ContentForm
from src.training.models import Topic


class TopicView(View):

    def get_object(self, request, *args, **kwargs):
        try:
            return Topic.objects.select_related('course__lang')\
                .get(slug=kwargs['topic'], course__slug=kwargs['course'])
        except Topic.DoesNotExist:
            raise Http404

    def get(self, request, *args, **kwargs):
        topic = self.get_object(request, *args, **kwargs)
        return render(
            request=request,
            template_name='training/topic/template.html',
            context={
                'object': topic,
                'course': topic.course,
            }
        )

    def post(self, request, *args, **kwargs):
        topic = self.get_object(request, *args, **kwargs)
        form = ContentForm(data=request.POST)
        response = form.perform_operation(topic)
        return JsonResponse(response.__dict__)

src/templates/groups/base.html
{% extends "base.html" %}
{% load groups_tags %}

{% block breadcrumbs %}
    {{ block.super }}
    {% show_breadcrumbs object %}
{% endblock %}

src/templates/groups/group.html
{% extends 'groups/base.html' %}

{% block content %}
    <div class="one-col group fp-content">
        <div class="group__col white">
            <h1 class="text-center">{{ object.title }}</h1>

            {% if object.content %}
                <div class="text">{{ object.content|safe }}</div>
            {% endif %}

            <table class="group__info">
                <tr><td>Год:</td><td>{{ object.creation_date.year }}</td></tr>
                <tr><td>Владелец:</td><td>{{ object.author }}</td></tr>
                {% if user_is_member %}
                    <tr><td>Статус:</td><td>Участник</td></tr>
                {% endif %}
            </table>
            {% if object.status == '0' %}
                {% if not user_is_member %}
                    {% if request.user.is_active %}
                        <p>Группа открыта для участия</p>
                        <form class="group__invite-form" method="POST">
                            {% csrf_token %}
                            <input type="submit" class="btn btn-primary" value="Стать участником" />
                        </form>
                    {% else %}
                    <p><a href="/login/">Авторизуйтесь</a> чтобы продолжить</p>
                    {% endif %}
                {% endif %}
            {% elif object.status == '1' %}
                <p>Закрытая группа</p>
            {% elif object.status == '2' %}
                {% if request.user.is_active %}
                    <p>Для участия в группе введите кодовое слово</p>
                    <form class="group__invite-form" method="POST">
                        {% csrf_token %}
                        <div class="form__col{% if form.errors %} error{% endif %}">
                            {{ form.code }}
                            <small class="field__msg">{{ form.errors.code.0 }}</small>
                        </div>
                        <input type="submit" class="btn btn-primary form__col" value="Отправить" />
                    </form>
                {% else %}
                    <p><a href="/login/">Авторизуйтесь</a> чтобы продолжить</p>
                {% endif %}
            {% endif %}

            {% if user_is_member or user_is_teacher %}
                {% if object.group_courses.all %}
                <h3>Учебная программа</h3>
                <table class="group__courses">
                    {% with object.group_courses.all as group_courses %}
                        {% for group_course in group_courses %}
                            <tr>
                                {% if group_courses|length > 1 %}
                                <td>{{ forloop.counter }}</td>
                                {% endif %}
                                <td>
                                    <a href="{{ group_course.course.get_absolute_url }}" target="_blank">{{ group_course.course }}</a>
                                    {% if group_course.show_table %}
                                        <a href="{% url 'groups:group-course' object.id group_course.id %}" target="_blank">[таблица результатов]</a></td>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% endwith %}
                </table>
                {% endif %}
            {% endif %}

        </div>
        {% if user_is_member or user_is_teacher %}
        <div class="group__col white">
            <h3 class="text-center">Список участников</h3>
            {% if object.members %}
                <div class="group__table-container">
                    <table class="group__table js__tablesorter">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Фамилия</th>
                                <th>Имя</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for member in object.members %}
                                <tr>
                                    <td>{{ forloop.counter }}</td>
                                    <td>{{ member.last_name }}</td>
                                    <td>{{ member.first_name }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% endif %}
        </div>
        {% endif %}
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>window.dispatchEvent(new Event('initTablesorter'))</script>
{% endblock %}

src/templates/groups/group_course.html
{% extends 'groups/base.html' %}

{% block content %}
    <div class="one-col group-course white">
        <h1>{{ object.group.title }}</h1>
        <h4>Результаты по курсу {{ object.course }}</h4>
        <form class="search__form" id="js__search-form" >
            <div class="input-group input-group-sm">
                <input type="text" name="search" class="form-control" id="js__search-input"
                       placeholder="Поиск участников, через запятую">
                <input type="submit" value="" title="поиск">
            </div>
        </form>
        <div class="course__fake-table-container js__course__fake-table-container">
            <div class="course__fake-table js__course__fake-table"></div>
        </div>
        <div class="course__table-container mb-4 js__course__table-container">
            <table class="course__table js__course__table js__tablesorter">
                <thead>
                    <tr>
                        <th class="wide">Участник</th>
                        <th class="wide">Решено</th>
                        <th class="wide">Баллы</th>
                        {% for topic in course_data.topics %}
                            {% for taskitem in topic.taskitems %}
                                <th data-sorter="false">
                                    {% if forloop.first %}
                                        <div class="caption"><span>{{ topic.number }} {{ topic.title }}</span></div>
                                    {% endif %}
                                    <a class="js__th-{{ topic.number }}-{{ forloop.counter }}" href="{{ taskitem.url }}"
                                       target="_blank" data-topic-title="{{ topic.number }} {{ topic.title }}" data-taskitem-title="{{ taskitem.number }} {{ taskitem.title }}">
                                        {{ taskitem.number }}
                                    </a>
                                </th>
                            {% endfor %}
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for member in object.group.members %}
                        <tr id="js__member-{{ member.id }}">
                            <td title="{{ member }}" class="wide js__username">{{ member.get_full_name }}</td>
                            <td class="js__total_solved_tasks wide"></td>
                            <td class="js__total_score wide"></td>
                            {% for topic in course_data.topics %}
                                {% for taskitem in topic.taskitems %}
                                    <td class="js__{{ taskitem.id }}" data-th=".js__th-{{ topic.number }}-{{ forloop.counter }}"></td>
                                {% endfor %}
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
       </div>

         <div class="loader js__loader">
             <div class="loader__bg"></div>
            <svg class="hourglass" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 206" preserveAspectRatio="none">
                <path class="middle" d="M120 0H0v206h120V0zM77.1 133.2C87.5 140.9 92 145 92 152.6V178H28v-25.4c0-7.6 4.5-11.7 14.9-19.4 6-4.5 13-9.6 17.1-17 4.1 7.4 11.1 12.6 17.1 17zM60 89.7c-4.1-7.3-11.1-12.5-17.1-17C32.5 65.1 28 61 28 53.4V28h64v25.4c0 7.6-4.5 11.7-14.9 19.4-6 4.4-13 9.6-17.1 16.9z"/>
                <path class="outer" d="M93.7 95.3c10.5-7.7 26.3-19.4 26.3-41.9V0H0v53.4c0 22.5 15.8 34.2 26.3 41.9 3 2.2 7.9 5.8 9 7.7-1.1 1.9-6 5.5-9 7.7C15.8 118.4 0 130.1 0 152.6V206h120v-53.4c0-22.5-15.8-34.2-26.3-41.9-3-2.2-7.9-5.8-9-7.7 1.1-2 6-5.5 9-7.7zM70.6 103c0 18 35.4 21.8 35.4 49.6V192H14v-39.4c0-27.9 35.4-31.6 35.4-49.6S14 81.2 14 53.4V14h92v39.4C106 81.2 70.6 85 70.6 103z"/>
            </svg>
        </div>

         <h4 class="mb-4">Обозначения:</h4>

         <table class="course__table-legend">
            <tr><td class="status__0"></td><td>Нет попыток</td></tr>
            <tr><td class="not-checked"></td><td>В процессе решения</td></tr>
            <tr><td class="status__1">-</td><td>Нет решения</td></tr>
            <tr><td class="status__2">4.5</td><td>Частично решено (c указанием кол-ва баллов)</td></tr>
            <tr><td class="status__3">+</td><td>Решено на максимальный балл</td></tr>
            <tr><td class="awaiting-check"></td><td>Отправлено на проверку (для режима ручной проверки)</td></tr>
            <tr><td class="not-count"></td><td>Решение вне зачета (баллы не засчитываются)</td></tr>
         </table>
    </div>
{% endblock %}


{% block js %}
    {{ block.super }}
    <script>
        window.groupCourseSolutionsUrl = "{% url 'groups:group-course-solutions' group_id=object.group.id group_course_id=object.id %}"
        window.dispatchEvent(new Event('groupCoursePageLoaded'))
    </script>
{% endblock js %}

src/templates/groups/groups_list.html
{% extends 'groups/base.html' %}

{% block content %}
    <div class="one-col groups">
        <div class="white fp-content">
            <h1 class="text-center">Учебные группы</h1>

            <form class="search__form">
                <div class="input-group input-group-sm">
                    {% csrf_token %}
                    {{ form.search }}
                    <input type="submit" value="" title="поиск" />
                </div>
            </form>
            {% if objects %}
                <div class="groups__table-container">
                    <table class="groups__table js__tablesorter">
                        <thead>
                            <tr>
                                <th>Название</th>
                                <th>Год</th>
                                <th>Владелец</th>
                                <th>Участников</th>
                                <th>Вступление в группу</th>
                                {% if request.user.is_active %}<th>Статус</th>{% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for group in objects %}
                                <tr>
                                    <td><a href="{% url 'groups:group' group_id=group.id %}" >{{ group.title }}</td>
                                    <td>{{ group.creation_date.year }}</td>
                                    <td>{{ group.author }}</td>
                                    <td>{{ group.members.count }}</td>
                                    <td>{{ group.get_status }}</td>
                                    {% if request.user.is_active %}
                                        <td>{% if request.user in group.members %}Участник{% endif %}</td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <p>Ничего не найдено!</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block js %}
    {{ block.super }}
    <script>window.dispatchEvent(new Event('initTablesorter'))</script>
{% endblock %}